services:

  ## Frontend development dockerfile and sync the files automatically
  frontend:
    build: 
      context: .
      dockerfile: ./services/frontend/develop.dockerfile
    develop: 
      watch: 
        - action: sync
          path: ./services/frontend
          target: /app/services/frontend
        - action: rebuild
          path: ./services/frontend/package.json

  ## Backend development dockerfile and sync the files automatically
  backend:
    build: 
      context: .
      dockerfile: ./services/backend/develop.dockerfile
    command: bun dev
    develop:
      watch: 
        - action: sync
          path: ./services/backend
          target: /app/services/backend
        - action: rebuild
          path: ./services/backend/package.json

## Direct access to the db
  timescaledb:
    ports:
    - "5432:5432"

## Apply migration at startup
  backend-migrations:
    develop: 
      watch: 
        - action: sync+restart
          path: ./services/backend/drizzle
          target: /app/services/backend/