# Updated compose.override.yaml
services:
  backend:
    build: 
      context: .
      dockerfile: ./services/backend/develop.dockerfile
    command: bun dev
    develop:
      watch: 
        - action: sync
          path: ./services/backend
          target: /app/services/backend
        - action: rebuild
          path: ./services/backend/package.json

## Used to automatically apply migration at startup
  backend-migrations:
    build:
      context: .
      dockerfile: ./services/backend/develop.dockerfile
    command: bun db:migrate
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      timescaledb: 
        condition: service_healthy

  frontend:
    build: 
      context: .
      dockerfile: ./services/frontend/develop.dockerfile
    develop: 
      watch: 
        - action: sync
          path: ./services/frontend
          target: /app/services/frontend
        - action: rebuild
          path: ./services/frontend/package.json

  timescaledb:
    ports:
    - "5432:5432"