services:
  ## The frontend service will build the frontend and then serve the files using caddy.

## The entrypoint of our app. This service will proxy requests to all other services. 
  caddy:
    profiles: [proxy]
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    networks:
      - proxy-network
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - caddy-data:/data
      - caddy-config:/config
      - /var/run/docker.sock:/var/run/docker.sock

  frontend: 
    profiles: [stateless]
    restart: unless-stopped
    build: 
      context: .
      dockerfile: ./services/frontend/dockerfile
    networks:
      - proxy-network
    labels:
      caddy: "${INTERFACE_FQDN}"
      caddy.encode: zstd gzip
      caddy.reverse_proxy: "{{upstreams 5173}}"

  ## The Backend will host our REST JSON api. Our spa will use this for data communication.
  backend: 
    profiles: [stateless]
    restart: unless-stopped
    build: 
      context: .
      dockerfile: ./services/backend/dockerfile
    networks:
      - default
      - proxy-network
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - MICROSOFT_TENANT_ID=${MICROSOFT_TENANT_ID}
      - MICROSOFT_CLIENT_ID=${MICROSOFT_CLIENT_ID}
      - MICROSOFT_CLIENT_SECRET=${MICROSOFT_CLIENT_SECRET}
      - MICROSOFT_REDIRECT_URI=${MICROSOFT_REDIRECT_URI}
      - PROD=${PROD}
    labels:
      caddy: "${INTERFACE_FQDN}"
      caddy.handle_0: /api/*
      caddy.handle_0.reverse_proxy: "{{upstreams 3000}}"
      caddy.handle_1: /.well-known/*
      caddy.handle_1.reverse_proxy: "{{upstreams 3000}}"
    depends_on:
      timescaledb: 
        condition: service_healthy

  ## A postgres database optimised for timeseries data
  timescaledb:
    profiles: [stateful]    
    image: timescale/timescaledb:latest-pg17
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - timescaledb-data:/var/lib/postgresql/data
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

## Apply migration at startup
  backend-migrations:
    profiles: [migrate]   
    build:
      context: .
      dockerfile: ./services/backend/develop.dockerfile
    command: bun db:migrate
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      timescaledb: 
        condition: service_healthy

volumes:
  timescaledb-data:
  caddy-data:
  caddy-config:

networks:
  proxy-network:
    name: proxy-network

