services:

  caddy:
    ports:
      - "3000:3000"

  ## Frontend development dockerfile and sync the files automatically
  frontend:
    build: 
      context: .
      dockerfile: ./services/frontend/develop.dockerfile
    develop: 
      watch: 
        - action: sync
          path: ./services/frontend
          target: /app/services/frontend
        - action: rebuild
          path: ./services/frontend/package.json

  ## Backend development dockerfile and sync the files automatically
  backend:
    build: 
      context: .
      dockerfile: ./services/backend/develop.dockerfile
    command: bun dev
    develop:
      watch: 
        - action: sync
          path: ./services/backend
          target: /app/services/backend
        - action: rebuild
          path: ./services/backend/package.json

## Direct access to the db
  timescaledb:
    ports:
    - "5432:5432"

#
#  studio:
#    profiles: [stateless]
#    build:
#      context: .
#      dockerfile: ./services/backend/develop.dockerfile
#    command: bun db:studio -- --host=0.0.0.0
#    ports:
#      - "4983:4983"
#    networks:
#      - default
#    environment:
#      - DATABASE_URL=${DATABASE_URL}
#    depends_on:
#      timescaledb: 
#        condition: service_healthy
        