services:

  ## The entrypoint of our app. This service will proxy requests to all other services. 
  caddy:
    profiles: [proxy]
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - caddy-data:/data
      - caddy-config:/config
      - /var/run/docker.sock:/var/run/docker.sock
    

  ## The frontend service will build the frontend and then store the build output in volume bind.
  frontend: 
    profiles: [stateless]
    build:
      context: services/frontend
      dockerfile: Dockerfile
    labels:
      caddy: "${INTERFACE_FQDN}"
      caddy.encode: zstd gzip
      caddy.reverse_proxy: "{{upstreams 8080}}"
    develop:
      watch:
        - action: rebuild
          path: ./services/frontend

  ## The Backend will host our REST JSON api. Our spa will use this for data communication.
  backend: 
    profiles: [stateless]
    build:
      context: services/backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@timescaledb:5432/${POSTGRES_DB}
    labels:
      caddy: "${INTERFACE_FQDN}"
      caddy.handle: /api/*
      caddy.handle.reverse_proxy: "{{upstreams 3000}}"
    depends_on:
      timescaledb:
        condition: service_healthy
        required: false
    develop:
      watch:
        - action: rebuild
          path: ./services/backend

  ## The ingestion server will allow vision systems to send data to the db. 
  ingest:
    profiles: [stateless]
    build:
      context: services/ingest
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@timescaledb:5432/${POSTGRES_DB}
    labels:
      caddy: "${INGEST_SERVER_FQDN}"
      caddy.reverse_proxy: "{{upstreams 50051}}"
    depends_on:
      timescaledb:
        condition: service_healthy
        required: false
    develop:
      watch:
        - action: rebuild
          path: ./services/ingest

  ## A postgres database optimised for timeseries data
  timescaledb:
    profiles: [stateful]    
    image: timescale/timescaledb:latest-pg17
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - timescaledb-data:/var/lib/postgresql/data
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  ## Production insights
  dozzle:
    profiles: [prod]   
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      caddy: "${DOZZLE_FQDN}"
      caddy.reverse_proxy: "{{upstreams 8080}}"

volumes:
  caddy-data:
  caddy-config:
  timescaledb-data:


