include: 
  - ./services/caddy/compose.yaml
  - ./services/portainer/compose.yaml

services:
  frontend: 
    profiles: [stateless]
    restart: unless-stopped
    build: 
      context: .
      dockerfile: ./services/frontend/dockerfile
    networks:
      - proxy-network
    labels:
      caddy: "${INTERFACE_FQDN}"
      caddy.encode: zstd gzip
      caddy.reverse_proxy: "{{upstreams 5173}}"

  ## The Backend will host our REST JSON api. Our spa will use this for data communication.
  backend: 
    profiles: [stateless]
    restart: unless-stopped
    build: 
      context: .
      dockerfile: ./services/backend/dockerfile
    networks:
      - default
      - proxy-network
    environment:
      - INTERFACE_FQDN=${INTERFACE_FQDN}
      - DATABASE_URL=${DATABASE_URL}
      - MICROSOFT_TENANT_ID=${MICROSOFT_TENANT_ID}
      - MICROSOFT_CLIENT_ID=${MICROSOFT_CLIENT_ID}
      - MICROSOFT_CLIENT_SECRET=${MICROSOFT_CLIENT_SECRET}
      - PROD=${PROD}
    labels:
      caddy: "${INTERFACE_FQDN}"
      caddy.handle_0: /api/*
      caddy.handle_0.reverse_proxy: "{{upstreams 3000}}"
      caddy.handle_1: /.well-known/*
      caddy.handle_1.reverse_proxy: "{{upstreams 3000}}"
    depends_on:
      timescaledb: 
        condition: service_healthy

  ## A postgres database optimised for timeseries data
  timescaledb:
    profiles: [stateful]    
    image: timescale/timescaledb:latest-pg17
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - timescaledb-data:/var/lib/postgresql/data
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

## Apply migration at startup
  migrate:
    profiles: [migrate]   
    build:
      context: .
      dockerfile: ./services/backend/develop.dockerfile
    command: bun db:migrate
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      timescaledb: 
        condition: service_healthy

volumes:
  timescaledb-data:
