
[upload]
url = "https://master-thesis.hjemmet.net/api/readings"
key = "6m84ML5JngJgb7xuZrLajN"

[docker]

[opcua]
url = "opc.tcp://192.168.200.11:4840"

[[opcua.node_ids]]
namespace = 6
variable = "::Program:l_status.encodersPhysical[0].value"
name = "position"
category = "plc"
unit = "mm"

[[opcua.node_ids]]
namespace = 6
variable = "::Program:l_status.encodersPhysical[0].speed"
name = "speed"
category = "plc"
unit = "mm/s"