FROM oven/bun

WORKDIR /app

# Copy package.json and bun.lockb
COPY package.json .
COPY bun.lockb .

# Install dependencies
RUN bun install

# Copy the rest of your app's source code
COPY . .

# Build your app
RUN bun run build

# The build output will be in /app/build