include: 
  - ../caddy/compose.yaml
  - ../timescaledb/compose.yaml

services:
  umami:
    profiles: [monitor]    
    image: ghcr.io/umami-software/umami:postgresql-latest
    restart: unless-stopped
    init: true
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_TYPE: postgresql
      APP_SECRET: random-string
    networks:
      - proxy-network
      - default
    labels:
      caddy: "${UMAMI_FQDN}"
      caddy.reverse_proxy: "{{upstreams 3000}}"
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:3000/api/heartbeat"]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      timescaledb: 
        condition: service_healthy