## The entrypoint of our app. This service will proxy requests to all other services. 
services:
  caddy:
    profiles: [proxy]
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    networks:
      - proxy_network
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - caddy-data:/data
      - caddy-config:/config
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  proxy_network:
    external: true

volumes:
  caddy-data:
  caddy-config:
