name: Build and test images

on: [push]

permissions:
  packages: write
  contents: read
  id-token: write

env:
  PROD: false
  IMAGE_TAG: 1.0

jobs:
  deploy-services:
    runs-on: ubuntu-latest
    environment: preview
    env:
      DOCKER_HOST: ssh://admin@${{ secrets.SERVER_IP }}
      COMPOSE_PROFILES: stateless, stateful, migrate
      INTERFACE_FQDN: https://preview.master-thesis.hjemmet.net
      MICROSOFT_TENANT_ID: ${{ secrets.MICROSOFT_TENANT_ID }}
      MICROSOFT_CLIENT_ID: ${{ secrets.MICROSOFT_CLIENT_ID }}
      MICROSOFT_CLIENT_SECRET: ${{ secrets.MICROSOFT_CLIENT_SECRET }}
      MICROSOFT_REDIRECT_URI: ${{ secrets.MICROSOFT_REDIRECT_URI }}
      POSTGRES_DB: database
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      DATABASE_URL: postgres://username:password@timescaledb:5432/database
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Deploy caddy
        run: docker compose --profile proxy -p proxy up -d
      - name: Deploy docker compose
        run: docker compose -f compose.yaml --profile stateful --profile stateless --profile migrate  up --build  -d
        env:
          COMPOSE_PROJECT_NAME: thesis-preview

