name: Build and test images

on: [push]

permissions:
  packages: write
  contents: read
  id-token: write

env:
  PROD: false
  IMAGE_TAG: 1.0

jobs:
  deploy-services:
    runs-on: ubuntu-latest
    environment: preview
    env:
      DOCKER_HOST: ssh://admin@${{ secrets.SERVER_IP }}
      COMPOSE_PROFILES: stateless, stateful, migrate
      POSTGRES_DB: ${{ vars.POSTGRES_DB }}
      INTERFACE_FQDN: ${{ vars.INTERFACE_FQDN }}
      MICROSOFT_REDIRECT_URI: ${{ vars.MICROSOFT_REDIRECT_URI }}

      MICROSOFT_TENANT_ID: ${{ secrets.MICROSOFT_TENANT_ID }}
      MICROSOFT_CLIENT_ID: ${{ secrets.MICROSOFT_CLIENT_ID }}
      MICROSOFT_CLIENT_SECRET: ${{ secrets.MICROSOFT_CLIENT_SECRET }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_USER }}

      DATABASE_URL: postgres://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_USER }}@timescaledb:5432/${{ vars.POSTGRES_DB }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Deploy caddy
        run: docker compose --profile proxy -p proxy up -d
      - name: Debug POSTGRES_DB secrets
        run: echo "$POSTGRES_DB"
      - name: Debug POSTGRES_USER secrets
        run: echo "$POSTGRES_USER"
      - name: Deploy docker compose
        run: docker compose -f compose.yaml --profile stateful --profile stateless --profile migrate  up --build  -d
        env:
          COMPOSE_PROJECT_NAME: thesis-preview
          DOCKER_HOST: ssh://admin@${{ secrets.SERVER_IP }}
          COMPOSE_PROFILES: stateless, stateful, migrate
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          INTERFACE_FQDN: ${{ secrets.INTERFACE_FQDN }}
          MICROSOFT_REDIRECT_URI: ${{ secrets.MICROSOFT_REDIRECT_URI }}

          MICROSOFT_TENANT_ID: ${{ secrets.MICROSOFT_TENANT_ID }}
          MICROSOFT_CLIENT_ID: ${{ secrets.MICROSOFT_CLIENT_ID }}
          MICROSOFT_CLIENT_SECRET: ${{ secrets.MICROSOFT_CLIENT_SECRET }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_USER }}



