name: Deploy

on: [push]

env:
  DOCKER_HOST: ssh://admin@${{ secrets.SERVER_IP }}
  COMPOSE_PROJECT_NAME: thesis-prod
  COMPOSE_PROFILES: proxy, stateless, stateful, 
  POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }} 
  INTERFACE_FQDN: https://master-thesis.hjemmet.net
  INGEST_FQDN: https://ingest.hjemmet.net
  DOZZLE_FQDN: https://dozzle.hjemmet.net
  
jobs:
  deploy-services:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Deploy docker compose
        run: docker compose up -d --build
