name: Create Server, Deploy and Test
on:
  workflow_dispatch:
    inputs:
      server_name:
        description: 'Name for the server'
        required: false
        default: 'nixos'
      ssh_key:
        description: 'Name of the SSH key registered in Hetzner Cloud'
        required: false
        default: 'deploy-key'
      type:
        description: 'The type of instance you would like for example "cx22" or "cx52"'
        required: false
        default: 'cx22'
      location:
        description: 'The hetzner location of choice, choose between "fsn1", "nbg1" or "hel1"'
        required: false
        default: 'hel1'

jobs:
  create-server:
    name: Create NixOS Server
    uses: ./.github/workflows/create-server.yml
    with:
      server_name: ${{ github.event.inputs.server_name }}
      ssh_key: ${{ github.event.inputs.ssh_key }}
      type: ${{ github.event.inputs.type }}
      location: ${{ github.event.inputs.location }}
    secrets:
      SSH_PRIVATE_KEY_2: ${{ secrets.SSH_PRIVATE_KEY_2 }}
      HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
      PASSWORD_HASH: ${{ secrets.PASSWORD_HASH }}
      
  deploy-backend:
    name: Deploy Backend Application
    needs: create-server
    uses: ./.github/workflows/deploy-backend.yml
    with:
      server_name: ${{ github.event.inputs.server_name }}
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_2 }}
      
  run-stress-test:
    name: Run Stress Tests
    needs: deploy-backend
    uses: ./.github/workflows/stress-test.yml
    with:
      server_name: ${{ github.event.inputs.server_name }}
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_2 }}