name: load-test

on:
  workflow-dispatch:

jobs:
  deploy:
    runs-on: windows-latest
    env:
      PROD: true
      COMPOSE_PROJECT_NAME: ${{ github.ref_name }}
      COMPOSE_PROFILES: stateless, stateful, migrate
      INTERFACE_FQDN: ${{ vars.INTERFACE_FQDN }}
      MICROSOFT_TENANT_ID: ${{ vars.MICROSOFT_TENANT_ID }}
      MICROSOFT_CLIENT_ID: ${{ secrets.MICROSOFT_CLIENT_ID }}
      MICROSOFT_CLIENT_SECRET: ${{ secrets.MICROSOFT_CLIENT_SECRET }}
      POSTGRES_DB: ${{ vars.POSTGRES_DB }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      DATABASE_URL: postgres://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@timescaledb:5432/${{ vars.POSTGRES_DB }}
      RESEND_CLIENT_SECRET: ${{ secrets.RESEND_CLIENT_SECRET }} 
      PORTAINER_FQDN: ${{ vars.PORTAINER_FQDN }}
      S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID}}
      S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
      S3_BUCKET: ${{ vars.S3_BUCKET }}
      S3_ENDPOINT: ${{ vars.S3_ENDPOINT }}
      IS_TEST: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          cd ci-cd/test_framework
          pip install hcloud requests

      - name: Run code
        run: python scaling_test.py
          
          