name: Preview

on:
  push:
    branches:
      - preview

jobs:
  check:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Check typescript errors (Backend)
        working-directory: services/backend
        run: bun check
      - name: Check typescript errors (Frontend)
        working-directory: services/frontend
        run: bun check

  format:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Check format (Backend)
        working-directory: services/backend
        run: bun x @biomejs/biome format ./src
      - name: Check format (Frontend)
        working-directory: services/frontend
        run: bun x prettier --check .

  lint:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Check lint (Backend)
        working-directory: services/backend
        run: bun x @biomejs/biome lint --error-on-warnings ./src
      - name: Check lint (Frontend)
        working-directory: services/frontend
        run: bun run lint

  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: Copy env file
        run: cp .env.example .env
      - name: Build Docker Images
        run: docker compose -f compose.yaml build

  unit-test:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: Copy env file
        run: cp .env.example .env
      - name: Compose up
        run: docker compose up backend timescaledb migrate --build -d
      - name: Wait 2 sec
        run: sleep 2
      - name: Unit test
        run: docker compose exec backend bun test