name: stress test
on:
  workflow_dispatch:
    inputs:
      server_name:
        description: 'Name for the server'
        required: false
        default: 'nixos'
      ssh_key:
        description: 'Name of the SSH key registered in Hetzner Cloud'
        required: false
        default: 'deploy-key'
      location:
        description: 'The hetzner location of choice, choose between "fsn1", "nbg1" or "hel1"'
        required: false
        default: 'hel1'
      type:
        description: 'The type of instance you would like for example "cx22" or "cx52"'
        required: false
        default: 'cx22'
jobs:
  create:
    runs-on: ubuntu-latest
    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_2 }}
      PASSWORD_HASH: ${{ secrets.PASSWORD_HASH }}
      HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Hetzner Cloud CLI
        uses: hetznercloud/setup-hcloud@v1
      - name: Setup k6 runtime
        uses: grafana/setup-k6-action@v1
        
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

      - name: Run NixOS Server
        working-directory: devops/nixos
        run: |
          ./create-server.sh "${{ github.event.inputs.server_name }}" "${{ github.event.inputs.ssh_key }}" "${{ github.event.inputs.location }}" "${{ github.event.inputs.type }}"
      - name: Set SERVER_IP environment variable
        run: |
          SERVER_IP=$(hcloud server ip "${{ github.event.inputs.server_name }}")
          echo "SERVER_IP=$SERVER_IP" >> $GITHUB_ENV
          echo "DOCKER_HOST=ssh://admin@$SERVER_IP" >> $GITHUB_ENV
      - name: Deploy backend
        run: |
          docker compose -f compose.yaml --env-file .env.test up backend timescaledb migrate --build -d --wait
          
      - name: Start stress test
        working-directory: services/test
        run: |
          k6 run load_test.js --env SERVER_IP=${{ env.SERVER_IP }}