name: Create Server, Deploy and Test
on:
  workflow_dispatch:
    inputs:
      server_name:
        description: 'Name for the server'
        required: false
        default: 'nixos'
      ssh_key:
        description: 'Name of the SSH key registered in Hetzner Cloud'
        required: false
        default: 'hans@ubuntu'
      type:
        description: 'The type of instance you would like for example "cx22" or "cx52"'
        required: false
        default: 'cpx21'
      location:
        description: 'The hetzner location of choice, choose between "fsn1", "nbg1" or "hel1"'
        required: false
        default: 'hil'
      num_cluster:
        description: 'Number of clusters to deploy'
        required: false
        default: '1'
      upload_key:
        description: 'The key to send CPU and memory usage to'
        required: false
        default: 'gfpoasp....'
jobs:
  create-deploy-test:
    runs-on: ubuntu-latest
    env:
      COMPOSE_PROJECT_NAME: test
      COMPOSE_PROFILES: stateless, stateful, migrate

      POSTGRES_DB: database
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      DATABASE_URL: postgres://username:password@timescaledb:5432/database

      INTERFACE_FQDN: http://localhost
      MICROSOFT_TENANT_ID: common
      MICROSOFT_CLIENT_ID: "d03453634..."
      MICROSOFT_CLIENT_SECRET: "jcmads...."
      RESEND_CLIENT_SECRET: "ADD YOUR KEY"
      PROD: true

      PORTAINER_FQDN: http://portainer.localhost

      S3_ACCESS_KEY_ID: "Your key here"
      S3_SECRET_ACCESS_KEY: "Your key here"
      S3_BUCKET: "Your key here"
      S3_ENDPOINT: "Your key here"

      IS_TEST: true
      NUM_CLUSTER: ${{ github.event.inputs.num_cluster }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_2 }}
      HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
      UPLOAD_KEY: ${{ github.event.inputs.upload_key }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Hetzner Cloud CLI
        uses: hetznercloud/setup-hcloud@v1
        
      - name: Setup k6 runtime
        uses: grafana/setup-k6-action@v1
        
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
          
      # Step 1: Create the server
      - name: Create NixOS Server
        working-directory: devops/nixos
        run: |
          ./create-server.sh "${{ github.event.inputs.server_name }}" "${{ github.event.inputs.ssh_key }}" "${{ secrets.PASSWORD_HASH }}" "${{ github.event.inputs.type }}" "${{ github.event.inputs.location }}"
          
      # Step 2: Set the server IP for later use
      - name: Set SERVER_IP environment variable
        run: |
          SERVER_IP=$(hcloud server ip "${{ github.event.inputs.server_name }}")
          echo "SERVER_IP=$SERVER_IP" >> $GITHUB_ENV
          echo "DOCKER_HOST=ssh://admin@$SERVER_IP" >> $GITHUB_ENV
          echo "Server created with IP: $SERVER_IP"
        
      - name: Docker info
        run: docker info

      - name: Deploy all services
        run: docker compose -f compose.yaml -f compose.test.yaml up backend timescaledb migrate -d
          
      - name: Wait
        run:  sleep 15

      - name: Check containers
        run:  docker compose ps
      
      # New steps to copy and run the ingest script on the server
      - name: Copy run_ingest script to server
        working-directory: services/test
        run: |
          # Make sure script is executable
          chmod +x run_ingest.sh
          # Copy the script to the server
          scp run_ingest.sh root@$SERVER_IP:/home/admin/run_ingest.sh
      
      - name: Execute ingest script on server
        run: |
          # Execute the script on the server with the upload key in the background
          ssh root@$SERVER_IP "bash /home/admin/run_ingest.sh \"$UPLOAD_KEY\"" &
          echo "Ingest script started in the background on server $SERVER_IP"
         
      - name: Run stress tests
        run: |
          echo "Starting stress test against $SERVER_IP..."
          echo "DOCKER_HOST=" >> $GITHUB_ENV
          docker compose -f compose.yaml -f compose.test.yaml run k6