name: Stress Test

on:
  workflow_call:
    inputs:
      server_name:
        description: 'Name of the server to test'
        required: true
        type: string
    secrets:
      SSH_PRIVATE_KEY:
        required: true
    outputs:
      test_result:
        description: "Summary of the stress test result"
        value: ${{ jobs.test.outputs.test_summary }}

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      test_summary: ${{ steps.run_test.outputs.summary }}
    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Hetzner Cloud CLI
        uses: hetznercloud/setup-hcloud@v1
        
      - name: Setup k6 runtime
        uses: grafana/setup-k6-action@v1
        
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
          
      - name: Set SERVER_IP environment variable
        run: |
          SERVER_IP=$(hcloud server ip "${{ inputs.server_name }}")
          echo "SERVER_IP=$SERVER_IP" >> $GITHUB_ENV
          
      - name: Start stress test
        id: run_test
        working-directory: services/test
        run: |
          k6 run load_test.js --env SERVER_IP=${{ env.SERVER_IP }}
          echo "summary=Stress test completed successfully" >> $GITHUB_OUTPUT