name: Create Server, Deploy and Test
on:
  workflow_dispatch:
    inputs:
      server_name:
        description: 'Name for the server'
        required: false
        default: 'nixos'
      ssh_key:
        description: 'Name of the SSH key registered in Hetzner Cloud'
        required: false
        default: 'deploy-key'
      type:
        description: 'The type of instance you would like for example "cx22" or "cx52"'
        required: false
        default: 'cx22'
      location:
        description: 'The hetzner location of choice, choose between "fsn1", "nbg1" or "hel1"'
        required: false
        default: 'hel1'

jobs:
  create-deploy-test:
    runs-on: ubuntu-latest
    environment: 'preview'
    env:
      PROD: false
      IS_TEST: false
      COMPOSE_PROJECT_NAME: ${{ github.ref_name }}
      COMPOSE_PROFILES: stateless, stateful, migrate
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_2 }}
      NUM_CLUSTER: ${{vars.NUM_CLUSTER}}
      HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
      INTERFACE_FQDN: ${{ vars.INTERFACE_FQDN }}
      MICROSOFT_TENANT_ID: ${{ vars.MICROSOFT_TENANT_ID }}
      MICROSOFT_CLIENT_ID: ${{ secrets.MICROSOFT_CLIENT_ID }}
      MICROSOFT_CLIENT_SECRET: ${{ secrets.MICROSOFT_CLIENT_SECRET }}
      POSTGRES_DB: ${{ vars.POSTGRES_DB }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      DATABASE_URL: postgres://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@timescaledb:5432/${{ vars.POSTGRES_DB }}
      RESEND_CLIENT_SECRET: ${{ secrets.RESEND_CLIENT_SECRET }} 
      PORTAINER_FQDN: ${{ vars.PORTAINER_FQDN }}
      S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID}}
      S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
      S3_BUCKET: ${{ vars.S3_BUCKET }}
      S3_ENDPOINT: ${{ vars.S3_ENDPOINT }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Hetzner Cloud CLI
        uses: hetznercloud/setup-hcloud@v1
        
      - name: Setup k6 runtime
        uses: grafana/setup-k6-action@v1
        
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
          
      # Step 1: Create the server
      - name: Create NixOS Server
        working-directory: devops/nixos
        run: |
          ./create-server.sh "${{ github.event.inputs.server_name }}" "${{ github.event.inputs.ssh_key }}" "${{ secrets.PASSWORD_HASH }}" "${{ github.event.inputs.type }}" "${{ github.event.inputs.location }}"
          
      # Step 2: Set the server IP for later use
      - name: Set SERVER_IP environment variable
        run: |
          SERVER_IP=$(hcloud server ip "${{ github.event.inputs.server_name }}")
          echo "SERVER_IP=$SERVER_IP" >> $GITHUB_ENV
          echo "DOCKER_HOST=ssh://admin@$SERVER_IP" >> $GITHUB_ENV
          echo "Server created with IP: $SERVER_IP"
        
      - name: Docker info
        run: docker info

      - name: Deploy all services
        run: docker compose up backend timescaledb migrate -d
          
      - name: Check containers
        run:  docker compose ps
          
      - name: Run stress tests
        working-directory: services/test
        run: |
          echo "Starting stress test against $SERVER_IP..."
          ./run_ingest.sh
          k6 run load_test.js --env SERVER_IP=${{ env.SERVER_IP }}