name: validation

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Check typescript errors (Backend)
        working-directory: services/backend
        run: bun check
      - name: Check typescript errors (Frontend)
        working-directory: services/frontend
        run: bun check

  format:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Check format (Backend)
        working-directory: services/backend
        run: bun x @biomejs/biome format ./src
      - name: Check format (Frontend)
        working-directory: services/frontend
        run: bun x prettier --check .

  lint:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Check lint (Backend)
        working-directory: services/backend
        run: bun x @biomejs/biome lint --error-on-warnings ./src
      - name: Check lint (Frontend)
        working-directory: services/frontend
        run: bun run lint

  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: Copy env file
        run: cp .env.example .env
      - name: Build Docker Images
        run: docker compose -f compose.yaml build

  unit-test:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: Compose up
        run: docker compose --env-file .env.example up backend timescaledb migrate --build -d --wait
      - name: Pause
        run: sleep 2
      - name: Unit test
        run: docker compose --env-file .env.example exec backend bun test --coverage
      - name: Dump Docker logs on failure
        if: ${{ failure() }}
        run: docker compose --env-file .env.example logs --timestamps --no-color
  
  playwright-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Copy env file
      run: cp .env.example .env
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install pnpm
      run: npm install -g pnpm
    - name: Install e2e dependencies
      working-directory: ./devops/e2e
      run: pnpm install
    - name: Install Playwright Browsers
      working-directory: ./devops/e2e
      run: pnpm exec playwright install --with-deps
    - name: Compose up
      run: docker compose -f compose.yaml up --build -d --wait
    - name: Pause
      run: sleep 2
    - name: Run Playwright tests
      working-directory: ./devops/e2e
      run: pnpm exec playwright test
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: devops/e2e/playwright-report/
        retention-days: 30